#!/bin/bash
rm $1.o
rm $1.lst
rm $1
rm $2.o
rm $2.lst
rm $2
nasm -g -f elf32 -F dwarf $1.asm -l $1.lst -o $1.o
nasm -g -f elf32 -F dwarf $2.asm -l $2.lst -o $2.o
ld -melf_i386 -o $1 $1.o $2.o


#nasm -f elf32 -F dwarf funcs.asm -l funcs.lst
#nasm -f elf32 -F dwarf main.asm -l main.lst
#ld -melf_i386 -o main main.o funcs.o
