;example of usage:	
	;in the c++ program, pass three parameters:
	;a filled arrays (1), an empty array of the same size (2), and the size of the array
	;calling "revArray(arr1, arr2, size)" will return the second array
	;the second array holds the reversed elements from the first array 
extern revArray

;example of usage:
	;in the c++ program, pass four parameters:
	; a filled array, another filled array, an empty array (all of the same size), and their size
	;calling "addTwoArrays(arr1, arr2, arr3, size)" will return the third array
	;the third array holds the summed values of the same indexed poition from array1 and 2
extern addTwoArrays

;example of usage:
	;in the c++ program, pass two parameters:
	;an integer a, and an integer b
	;calling "addTwo(a, b)" will return the sum of these integers
extern addTwo

;example of usage:
	;in the c++ program, pass two parameters:
	; an integer a, and an integer b
	;calling "multiplyTwo(a, b)" will return the product of those two integers
extern multiplyTwo

;example of usage:
	;in the c++ program, pass one parameter:
	;pass an integer
	;calling "pow2(a)" will return the squared value of that integer
extern pow2

;example of usage:
	;in the c++ program, pass two parameters:
	; a filled array, and an integer representing its size
	;calling "addArray(arr1, size)" will return the summed value of all the element in the array
extern addArray

