#!/bin/bash
rm $1.o
rm $1.lst
rm $1
nasm -g -f elf64 -F dwarf $1.asm -l $1.lst

nasm -f elf64 -F dwarf -g stats.asm -l stats.lst
ld $1.o ./functions64.o ./stats.o -o $1
#ld main.o ./functions64.o ./stats.o -o main
